ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.transferspiketrap]
path = "out/ERC20TransferSpikeTrap.sol/ERC20TransferSpikeTrap.json"
response_contract = "0x7788749c85306f989393ba7b4A7DDA6920657D41"
response_function = "respondWithERC20VolumeContext(address,uint256,uint256)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 2
private_trap = true
whitelist = ["0x04C4762BB1923c55Ea782967D4CA78f42B4E21E5"]
address = "0x85515427C38213951B1f0D62e6bc8D4E0e2E599C"
